# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='time_sended',
            new_name='time_sent',
        ),
    ]
