# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'empty', max_length=500)),
                ('kind', models.CharField(choices=[(b'0', b'general'), (b'1', b'appointment'), (b'2', b'payment'), (b'3', b'chat ')], default=b'0', max_length=1)),
                ('status', models.CharField(choices=[(b'0', b'created'), (b'1', b'active'), (b'2', b'solved'), (b'3', b'problematic')], default=b'0', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
