# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20161029_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='kind',
            field=models.CharField(choices=[(b'0', b'general'), (b'1', b'appointment'), (b'2', b'payment'), (b'3', b'chat ')], default=b'0', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
