# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 23:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(default=b'', max_length=250)),
                ('device_type', models.SmallIntegerField(choices=[(1, b'Android'), (2, b'iPhone'), (3, b'Chrome'), (4, b'Others')])),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRequeriments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=b'', max_length=50)),
                ('document_name', models.CharField(default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPasswordResetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=b'11e482c1-60ce-4812-995d-789a02b26aba', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'avatar/user_uploads/')),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=0)),
                ('nationality', models.CharField(max_length=50)),
                ('member_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(default=b'356cd7bb-808a-49ca-8783-ff163bb9be4c', max_length=50)),
                ('key_expires', models.DateTimeField(default=datetime.datetime(2016, 8, 23, 23, 48, 18, 320656))),
                ('is_verified', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('lat', models.CharField(default=b'0', max_length=30)),
                ('lon', models.CharField(default=b'0', max_length=30)),
                ('role', models.CharField(default=b'none', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profiles',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
