# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 23:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160821_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'37f5a5b6-dbd6-49b5-9102-434ec29b2728', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'be296534-7091-4919-8df1-47a10a7de7af', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 23, 48, 38, 574103)),
        ),
    ]
