# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160821_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'0668d103-6c1e-4402-9100-49de932a9ae5', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'2e1d610f-2222-4777-9f48-3abde7a39d1f', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 23, 49, 34, 431216)),
        ),
    ]
