# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 23:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160821_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'91d91905-c6b3-4ebb-879f-59ab61325516', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'2f8f34ed-27d6-4729-9cdd-0efc96587bfa', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 23, 58, 21, 446520)),
        ),
    ]
