# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160821_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.SmallIntegerField(choices=[(1, b'Android'), (2, b'iPhone'), (3, b'Chrome'), (4, b'Others')], default=1),
        ),
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'a9e66afd-2223-42f7-bb51-bf7069f2c340', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'87f78950-9a72-4153-b107-6bc539776572', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 0, 4, 26, 251934)),
        ),
    ]
