# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 05:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20160822_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'1daf520f-d720-41d6-8a2a-19bf80f6d3f5', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'5e4bea9b-e6eb-41eb-b660-8099535566f9', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 5, 24, 24, 182130)),
        ),
    ]
