# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20160822_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'8565305a-9f2c-447f-b2c7-442a96d4b611', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'c547c57c-0d72-4ac6-86de-b4c16cf8d1df', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 5, 31, 0, 812340)),
        ),
    ]
