# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20160822_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'5e9b28e1-8aca-4e1e-bcda-21101793df28', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'ec70a258-0f28-450c-b664-6b6532353f4d', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 5, 36, 13, 292147)),
        ),
    ]
