# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20160822_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'0b851b3c-6420-4305-a8c8-feae85594a61', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'a5cebe90-6c56-4b9e-8bd8-0f57431f3cb3', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 2, 56, 2, 52340)),
        ),
    ]
