# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20160827_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_new',
        ),
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'29a766ee-0af8-47ac-a554-de244914d21d', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'fcd54287-707f-49a3-a00f-e8bd67c5acd7', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 19, 4, 4, 554309)),
        ),
    ]
