# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20160830_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'5668b105-6173-46c2-8eba-b786b7ac6915', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'170e5ea5-c626-42b1-947f-d7186d253bf1', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 13, 29, 58, 151159)),
        ),
    ]
