# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20160905_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'67d801c2-84b0-4ab2-9400-c36ecae26a0b', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'390430ec-5ef6-46ee-a061-9f3936299bff', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 15, 10, 56, 984017)),
        ),
    ]
