# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20160906_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'e0b72d25-ea87-4528-ac54-7e752e3bebb0', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'f0f4ca2d-73f2-43e9-86e4-11cb9e87fbce', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 9, 14, 47, 36, 673566)),
        ),
    ]
