# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20160910_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'ad3a23ac-a64d-4ab9-9524-8a4d8dae238d', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'bdbaef06-ce8c-48df-bad9-a179a33b54b3', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 28, 21, 20, 46, 827963)),
        ),
    ]
