# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20160926_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'dbe5baf5-b800-49ef-9aca-6ab82e11c4cb', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'00e99078-a71a-4453-ba8c-719bec95b60e', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 3, 16, 56, 29, 357742)),
        ),
    ]
