# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20161001_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'8b3f6028-ba17-4281-9866-9d348b8cbcca', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'5c497012-d29a-4e88-b174-67986a225e9e', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 0, 29, 43, 60275)),
        ),
    ]
