# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20161002_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'87e5e45f-5f6a-4648-9157-8d522d919766', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'e4549543-63b3-4016-9d72-5d4297b10346', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 12, 18, 45, 98706)),
        ),
    ]
