# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20161005_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'9d1b454d-728e-4f76-a40d-41372c5d1f5c', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'59d31941-94fb-4744-b86e-e29e4c3b41c9', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 7, 12, 20, 21, 609389)),
        ),
    ]
