# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20161005_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_tag',
            field=models.CharField(default=b'no_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'3dff626a-110c-4d06-88c2-df181f4174a9', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'fd66787b-bafd-45dc-9a20-bbfd3404bcc6', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 14, 7, 27, 53, 145289)),
        ),
    ]
