# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20161022_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'b9a38a64-4a32-40ea-8fc9-543de502821f', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'9479a6bc-4de3-4a46-9261-90d5a01d0b8c', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 16, 2, 23, 886437)),
        ),
    ]
