# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20161028_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'e9152084-e0d6-407e-a871-8c8034976e62', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'f0c34534-884e-4771-8322-592034f0859b', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 21, 24, 48, 236261)),
        ),
    ]
