# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20161029_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpasswordresetrequest',
            name='key',
            field=models.CharField(default=b'978197d7-fa77-4da6-8aa3-59971b37410a', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default=b'149a5d15-5a2c-4534-981f-3c17657a9ecd', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 22, 6, 21, 921114)),
        ),
    ]
