# Generated by Django 2.1.2 on 2018-10-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(default='empty', max_length=100)),
                ('host_fcm_token', models.CharField(default='', max_length=250)),
                ('guest', models.TextField(default='empty', max_length=100)),
                ('guest_fcm_token', models.CharField(default='', max_length=250)),
                ('board', models.TextField(default='EEEEEEEEE', max_length=9)),
                ('state', models.TextField(default='empty', max_length=100)),
                ('turn', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('state',),
            },
        ),
    ]
