# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20160821_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'0', b'request_created'), (b'1', b'docs_found'), (b'2', b'waiting_doc_confirmation'), (b'3', b'doc_going_to_place'), (b'4', b'doctor_arrived'), (b'5', b'appointment'), (b'6', b'payment'), (b'7', b'feedback')], default=b'0', max_length=1)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lon', models.CharField(default=b'0', max_length=30)),
                ('lat', models.CharField(default=b'0', max_length=30)),
                ('address', models.CharField(default=b'', max_length=50)),
                ('city', models.CharField(default=b'', max_length=50)),
                ('causes', models.TextField(default=b'', max_length=500)),
                ('time_range1', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_range2', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='account.UserProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='account.UserProfile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=b'', max_length=500)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
