# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20160905_1329'),
        ('appointments', '0002_auto_20160822_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sended', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(default=b'empty', max_length=500)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='account.UserProfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='account.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnostic',
            field=models.TextField(default=b'', max_length=2500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='causes',
            field=models.TextField(default=b'', max_length=2500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(b'0', b'created'), (b'1', b'paid'), (b'2', b'assigned'), (b'3', b'attended'), (b'4', b'issued')], default=b'0', max_length=1),
        ),
    ]
