# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_auto_20160905_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedicRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_type', models.CharField(choices=[(b'0', b'disease'), (b'1', b'surgery'), (b'2', b'other')], default=b'2', max_length=1)),
                ('description', models.TextField(default=b'', max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(b'0', b'created'), (b'1', b'paid'), (b'2', b'assigned'), (b'3', b'attended'), (b'4', b'problematic')], default=b'0', max_length=1),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
