# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0004_auto_20160905_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLegalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('diploma', models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'documents/user_uploads/')),
                ('degree_certificate', models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'documents/user_uploads/')),
                ('social_work_certificate', models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'documents/user_uploads/')),
                ('rethus_register', models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'documents/user_uploads/')),
                ('cmc_id', models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'documents/user_uploads/')),
                ('liability_policy', models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'documents/user_uploads/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
