# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_icd_10_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlegalprofile',
            name='cmc_id_verified',
        ),
        migrations.RemoveField(
            model_name='doctorlegalprofile',
            name='degree_certificate_verified',
        ),
        migrations.RemoveField(
            model_name='doctorlegalprofile',
            name='diploma_verified',
        ),
        migrations.RemoveField(
            model_name='doctorlegalprofile',
            name='liability_policy_verified',
        ),
        migrations.RemoveField(
            model_name='doctorlegalprofile',
            name='rethus_register_verified',
        ),
        migrations.RemoveField(
            model_name='doctorlegalprofile',
            name='social_work_certificate_verified',
        ),
        migrations.AddField(
            model_name='doctorlegalprofile',
            name='cmc_id_state',
            field=models.CharField(choices=[(b'0', b'pending'), (b'1', b'sent'), (b'2', b'valid'), (b'3', b'invalid')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorlegalprofile',
            name='degree_certificate_state',
            field=models.CharField(choices=[(b'0', b'pending'), (b'1', b'sent'), (b'2', b'valid'), (b'3', b'invalid')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorlegalprofile',
            name='diploma_state',
            field=models.CharField(choices=[(b'0', b'pending'), (b'1', b'sent'), (b'2', b'valid'), (b'3', b'invalid')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorlegalprofile',
            name='liability_policy_state',
            field=models.CharField(choices=[(b'0', b'pending'), (b'1', b'sent'), (b'2', b'valid'), (b'3', b'invalid')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorlegalprofile',
            name='rethus_register_state',
            field=models.CharField(choices=[(b'0', b'pending'), (b'1', b'sent'), (b'2', b'valid'), (b'3', b'invalid')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorlegalprofile',
            name='social_work_certificate_state',
            field=models.CharField(choices=[(b'0', b'pending'), (b'1', b'sent'), (b'2', b'valid'), (b'3', b'invalid')], default=b'0', max_length=1),
        ),
    ]
