# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20161028_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorlegalprofile',
            options={'verbose_name': 'Doctor Legal Profile', 'verbose_name_plural': 'Doctors Legal Profiles'},
        ),
        migrations.AlterField(
            model_name='doctorlegalprofile',
            name='cmc_id_state',
            field=models.IntegerField(choices=[(0, b'pending'), (1, b'sent'), (2, b'valid'), (3, b'invalid')], default=0),
        ),
        migrations.AlterField(
            model_name='doctorlegalprofile',
            name='degree_certificate_state',
            field=models.IntegerField(choices=[(0, b'pending'), (1, b'sent'), (2, b'valid'), (3, b'invalid')], default=0),
        ),
        migrations.AlterField(
            model_name='doctorlegalprofile',
            name='diploma',
            field=models.ImageField(default=b'avatar/no_avatar.png', upload_to=b'IntegerField/user_uploads/'),
        ),
        migrations.AlterField(
            model_name='doctorlegalprofile',
            name='diploma_state',
            field=models.IntegerField(choices=[(0, b'pending'), (1, b'sent'), (2, b'valid'), (3, b'invalid')], default=0),
        ),
        migrations.AlterField(
            model_name='doctorlegalprofile',
            name='liability_policy_state',
            field=models.IntegerField(choices=[(0, b'pending'), (1, b'sent'), (2, b'valid'), (3, b'invalid')], default=0),
        ),
        migrations.AlterField(
            model_name='doctorlegalprofile',
            name='rethus_register_state',
            field=models.IntegerField(choices=[(0, b'pending'), (1, b'sent'), (2, b'valid'), (3, b'invalid')], default=0),
        ),
        migrations.AlterField(
            model_name='doctorlegalprofile',
            name='social_work_certificate_state',
            field=models.IntegerField(choices=[(0, b'pending'), (1, b'sent'), (2, b'valid'), (3, b'invalid')], default=0),
        ),
    ]
